grammar<'input>;

use lalrpop_util::ParseError;

use crate::front::{ast::*, lexer::Token};

extern {
  type Location = usize;

  /// Lexical tokens used in parsing
  enum Token<'input> {
    "{" => Token::LBrace,
    "}" => Token::RBrace,
    "(" => Token::LParen,
    ")" => Token::RParen,
    "[" => Token::LBracket,
    "]" => Token::RBracket,
    ";" => Token::Semicolon,
    "." => Token::Period,
    "," => Token::Comma,
    ":" => Token::Colon,
    "?" => Token::Question,
    "=" => Token::Equal,
    "+" => Token::Plus,
    "-" => Token::Hyphen,
    "*" => Token::Asterisk,
    "/" => Token::FSlash,
    "%" => Token::Percent,
    "&" => Token::Ampersand,
    "|" => Token::Pipe,
    "^" => Token::Caret,
    "~" => Token::Tilde,
    "!" => Token::Bang,
    "<" => Token::Lt,
    ">" => Token::Gt,

    "++" => Token::PlusPlus,
    "--" => Token::HyphenHyphen,
    "&&" => Token::AmpersandAmpersand,
    "||" => Token::PipePipe,
    "<<" => Token::LtLt,
    ">>" => Token::GtGt,
    "==" => Token::EqualEqual,
    "+=" => Token::PlusEqual,
    "-=" => Token::HyphenEqual,
    "*=" => Token::AsteriskEqual,
    "/=" => Token::FSlashEqual,
    "%=" => Token::PercentEqual,
    "&=" => Token::AmpersandEqual,
    "|=" => Token::PipeEqual,
    "^=" => Token::CaretEqual,
    "!=" => Token::BangEqual,
    "<=" => Token::LtEqual,
    ">=" => Token::GtEqual,
    "->" => Token::Arrow,
    "[]" => Token::LBracketRBracket,

    "<<=" => Token::LtLtEqual,
    ">>=" => Token::GtGtEqual,

    "true" => Token::True,
    "false" => Token::False,
    "number" => Token::Number(<i64>),
    "ident" => Token::Ident(<&'input str>),
    "null" => Token::Null,

    "void" => Token::Void,
    "int" => Token::Int,
    "bool" => Token::Bool,
    "typedef" => Token::Typedef,
    "struct" => Token::Struct,

    "alloc" => Token::Alloc,
    "alloc_array" => Token::AllocArray,

    "if" => Token::If,
    "else" => Token::Else,
    "while" => Token::While,
    "for" => Token::For,
    "return" => Token::Return,
    "assert" => Token::Assert,
  }
}

/// The program is a collection of global declarations
pub Program : ProgramAST = {
  <GDecl*> => <>,
};

/// Global declarations
GDecl : GlobalDeclaration = {
  // functions
  <FDecl> => <>,
  <FDefn> => <>,
  // structs
  <SDecl> => <>,
  <SDefn> => <>,
  // typedefs
  <TDefn> => <>,
};

/// Function declaration
FDecl : GlobalDeclaration = {
  <t : ReturnType> <i : Ident> <p : ParamList> ";" => GlobalDeclaration::FDecl(t, i, p),
};

/// Function definition
FDefn : GlobalDeclaration = {
  <t : ReturnType> <i : Ident> <p : ParamList> <b : Block> => GlobalDeclaration::FDefn(t, i, p, b),
};

/// Struct declaration
SDecl : GlobalDeclaration = {
  "struct" <i : Ident> ";" => GlobalDeclaration::SDecl(i),
};

/// Struct definition
SDefn : GlobalDeclaration = {
  "struct" <i : Ident> "{" <f : SField*> "}" ";" => GlobalDeclaration::SDefn(i, f),
};

/// Struct field variables
SField : Variable = {
  <t : Type> <i : Ident> ";" => (t, i),
};

/// Type definition
TDefn : GlobalDeclaration = {
  "typedef" <t : Type> <i : Ident> ";" => GlobalDeclaration::TDefn(t, i),
};

/// Fundamental non-void supported C0 types
BaseType : Typ = {
  "int" => Typ::Int,
  "bool" => Typ::Bool,
  "struct" <i : Ident> => Typ::Struct(i),
};

/// Types that can be prefixes for pointers/arrays
PrefixType : Typ = {
  <BaseType> => <>,
  <i : Ident> => Typ::Typedef(i),
};

/// Pointer/array suffixes on base types
SuffixType : bool = {
  <PointerSuffix> => true,
  <ArraySuffix> => false,
};
PointerSuffix : () = {
  "*" => (),
};
ArraySuffix : () = {
  "[]" => (),
};

/// Function return types
ReturnType : Typ = {
  "void" => Typ::Void,
  <Type> => <>,
};

/// Non-void types
Type : Typ = {
  <p : PrefixType> <s : SuffixType*> => {
    let mut out = p;
    for is_pointer in s {
      out = if is_pointer {
        if let Typ::Pointer(ptr_val, depth) = out {
          Typ::Pointer(ptr_val, depth + 1)
        } else {
          Typ::Pointer(Box::new(out), 1)
        }
      } else {
        if let Typ::Array(array_val, depth) = out {
          Typ::Array(array_val, depth + 1)
        } else {
          Typ::Array(Box::new(out), 1)
        }
      };
    }
    out
  },
};

/// Grammar that is ambiguous for pointer or multiply
PointeryDecl : (Ident, usize) = {
  <i : Ident> <s : PointerSuffix+> => (i, s.len()),
};

/// Types used within declaration statements
DeclType : Typ = {
  <t : BaseType> <s : SuffixType*> => {
    let mut out = t;
    for is_pointer in s {
      out = if is_pointer {
        if let Typ::Pointer(ptr_val, depth) = out {
          Typ::Pointer(ptr_val, depth + 1)
        } else {
          Typ::Pointer(Box::new(out), 1)
        }
      } else {
        if let Typ::Array(array_val, depth) = out {
          Typ::Array(array_val, depth + 1)
        } else {
          Typ::Array(Box::new(out), 1)
        }
      };
    }
    out
  },
  <i : Ident> <_a : ArraySuffix> <s : SuffixType*> => {
    let mut out = Typ::Array(Box::new(Typ::Typedef(i)), 1);
    for is_pointer in s {
      out = if is_pointer {
        if let Typ::Pointer(ptr_val, depth) = out {
          Typ::Pointer(ptr_val, depth + 1)
        } else {
          Typ::Pointer(Box::new(out), 1)
        }
      } else {
        if let Typ::Array(array_val, depth) = out {
          Typ::Array(array_val, depth + 1)
        } else {
          Typ::Array(Box::new(out), 1)
        }
      };
    }
    out
  },
  <p : PointeryDecl> <_a : ArraySuffix> <s : SuffixType*> => {
    let mut out = Typ::Array(Box::new(Typ::Pointer(Box::new(Typ::Typedef(p.0)), p.1)), 1);
    for is_pointer in s {
      out = if is_pointer {
        if let Typ::Pointer(ptr_val, depth) = out {
          Typ::Pointer(ptr_val, depth + 1)
        } else {
          Typ::Pointer(Box::new(out), 1)
        }
      } else {
        if let Typ::Array(array_val, depth) = out {
          Typ::Array(array_val, depth + 1)
        } else {
          Typ::Array(Box::new(out), 1)
        }
      };
    }
    out
  },
};

/// Numeric immediate
Number : i64 = {
  <n : "number"> => n,
};

/// Boolean immediate
Boolean : bool = {
  "true" => true,
  "false" => false,
};

/// Identifier
Ident : String = {
  <i : "ident"> => i.to_owned(),
};

/// Function parameter list
ParamList : Vec<Variable> = {
  "(" ")" => vec![],
  "(" <p : Param> <pf : ParamFollow*> ")" => std::iter::once(p).chain(pf.into_iter()).collect::<Vec<Variable>>(),
};

/// Function parameter
Param : Variable = {
  <t : Type> <i : Ident> => (t, i),
};

/// Function parameter following a previous one
ParamFollow : Variable = {
  "," <Param> => <>,
};

/// Statement
Stmt : Stmt = {
  <Matched> => <>,
  <Unmatched> => <>,
};

/// Statements that don't suffer from dangling else
Matched : Stmt = {
  <Simp> ";" => <>,
  <Block> => <>,
  "while" "(" <e : Expr> ")" <m : Matched> => Stmt::While(e, Box::new(m)),
  "for" "(" <i : Simp?> ";" <e : Expr> ";" <s : SimpNoDecl?> ")" <m : Matched> => Stmt::For(Box::new(i), e, Box::new(s), Box::new(m)),
  "return" <e : Expr?> ";" => Stmt::Ret(e),
  "if" "(" <e : Expr> ")" <m1 : Matched> "else" <m2 : Matched> => Stmt::Cond(e, Box::new(m1), Box::new(m2)),
  "assert" "(" <e : Expr> ")" ";" => Stmt::Assert(e),
};

/// Statements that suffer from dangling else
Unmatched : Stmt = {
  "if" "(" <e : Expr> ")" <s : Stmt> => Stmt::Cond(e, Box::new(s), Box::new(Stmt::NoOp())),
  "if" "(" <e : Expr> ")" <m : Matched> "else" <u : Unmatched> => Stmt::Cond(e, Box::new(m), Box::new(u)),
  "while" "(" <e : Expr> ")" <u : Unmatched> => Stmt::While(e, Box::new(u)),
  "for" "(" <i : Simp?> ";" <e : Expr> ";" <s : SimpNoDecl?> ")" <u : Unmatched> => Stmt::For(Box::new(i), e, Box::new(s), Box::new(u)),
};

/// An ordered block of statements
Block : Stmt = {
  "{" <s : Stmt*> "}" => Stmt::Block(s),
};

/// New variable declaration
Decl : Stmt = {
  <t : DeclType> <i : Ident> => Stmt::Decl((t, i)),
  <t : DeclType> <i : Ident> "=" <e : Expr> => Stmt::Defn((t, i), e),
  <t : Ident> <i : Ident> => Stmt::Decl((Typ::Typedef(t), i)),
  <t : Ident> <i : Ident> "-" <e : Expr> => Stmt::Defn((Typ::Typedef(t), i), e),
};

/// Simple statements
Simp : Stmt = {
  <Decl> => <>,
  <SimpNoDecl> => <>,
};

/// Simple statements that don't result in new variable declarations
SimpNoDecl : Stmt = {
  <l : Postfix> <o : PostOp> => match o {
    PostOp::Inc => Stmt::Asgn(l, AsnOp::Plus, Expr::Number(1)),
    PostOp::Dec => Stmt::Asgn(l, AsnOp::Minus, Expr::Number(1)),
  },
  <l : Expr> <o : AsnOp> <e : Expr> => Stmt::Asgn(l, o, e),
  <e : Expr> => Stmt::Expr(e),
};

/// Expressions chained to preserve operations priority order
Expr : Expr = {
  <c : LOr> "?" <i : Expr> ":" <e : Expr> => Expr::Ternop(Box::new(c), Box::new(i), Box::new(e), None),
  <LOr> => <>,
};
LOr : Expr = {
  <l : LAnd> <rest : (LOrOp LAnd)*> => {
    let mut expr = l;
    for (op, rhs) in rest {
      expr = Expr::Binop(Box::new(expr), op, Box::new(rhs), None);
    }
    expr
  },
};
LAnd : Expr = {
  <l : BOr> <rest : (LAndOp BOr)*> => {
    let mut expr = l;
    for (op, rhs) in rest {
      expr = Expr::Binop(Box::new(expr), op, Box::new(rhs), None);
    }
    expr
  },
};
BOr : Expr = {
  <l : BXor> <rest : (BOrOp BXor)*> => {
    let mut expr = l;
    for (op, rhs) in rest {
      expr = Expr::Binop(Box::new(expr), op, Box::new(rhs), None);
    }
    expr
  },
};
BXor : Expr = {
  <l : BAnd> <rest : (BXorOp BAnd)*> => {
    let mut expr = l;
    for (op, rhs) in rest {
      expr = Expr::Binop(Box::new(expr), op, Box::new(rhs), None);
    }
    expr
  },
};
BAnd : Expr = {
  <l : Eq> <rest : (BAndOp Eq)*> => {
    let mut expr = l;
    for (op, rhs) in rest {
      expr = Expr::Binop(Box::new(expr), op, Box::new(rhs), None);
    }
    expr
  },
};
Eq : Expr = {
  <l : Rel> <rest : (EqOp Rel)*> => {
    let mut expr = l;
    for (op, rhs) in rest {
      expr = Expr::Binop(Box::new(expr), op, Box::new(rhs), None);
    }
    expr
  },
};
Rel : Expr = {
  <l : Shift> <rest : (RelOp Shift)*> => {
    let mut expr = l;
    for (op, rhs) in rest {
      expr = Expr::Binop(Box::new(expr), op, Box::new(rhs), None);
    }
    expr
  },
};
Shift: Expr = {
  <l : Add> <rest : (ShiftOp Add)*> => {
    let mut expr = l;
    for (op, rhs) in rest {
      expr = Expr::Binop(Box::new(expr), op, Box::new(rhs), None);
    }
    expr
  },
};
Add : Expr = {
  <l : Mul> <rest : (AddOp Mul)*> => {
    let mut expr = l;
    for (op, rhs) in rest {
      expr = Expr::Binop(Box::new(expr), op, Box::new(rhs), None);
    }
    expr
  },
};
Mul : Expr = {
  <StrictMul> => <>,
  <Unary> => <>,
};
StrictMul : Expr = {
  <p : Pointery> <u : UnaryNoDeref> => {
    let rhs = if p.1 > 1 {
      Expr::Deref(Box::new(u), p.1 - 1, None)
    } else {
      u
    };
    Expr::Binop(Box::new(p.0), BinOp::Mul, Box::new(rhs), None)
  },
  <p : PointeryDecl> <u : UnaryNoDeref> => {
    let rhs = if p.1 > 1 {
      Expr::Deref(Box::new(u), p.1 - 1, None)
    } else {
      u
    };
    Expr::Binop(Box::new(Expr::Variable(p.0, None)), BinOp::Mul, Box::new(rhs), None)
  },
  <l : StrictMul> "*" <r : Unary> => Expr::Binop(Box::new(l), BinOp::Mul, Box::new(r), None),
  <l : Mul> "/" <r : Unary> => Expr::Binop(Box::new(l), BinOp::Div, Box::new(r), None),
  <l : Mul> "%" <r : Unary> => Expr::Binop(Box::new(l), BinOp::Mod, Box::new(r), None),
};
Pointery : (Expr, usize) = {
  <u : UnaryNoIdent> <p : PointerSuffix+> => (u, p.len()),
};
Unary : Expr = {
  "*" <e : Unary> => Expr::Deref(Box::new(e), 1, None),
  <UnaryNoDeref> => <>,
};
UnaryNoDeref : Expr = {
  <UnaryBase> => <>,
  <Postfix> => <>,
};
UnaryNoIdent : Expr = {
  "*" <e : Unary> => Expr::Deref(Box::new(e), 1, None),
  <UnaryBase> => <>,
  <PostfixNoIdent> => <>,
};
UnaryBase : Expr = {
  <o : UnOp> <e : Unary> => match (o, &e) {
    (UnOp::Neg, Expr::Number(a)) => Expr::Number(-1 * (*a)),
    (UnOp::Not, Expr::Number(a)) => Expr::Number(!(*a)),
    (UnOp::LNot, Expr::Bool(a)) => Expr::Bool(!a),
    _ => Expr::Unop(o, Box::new(e), None),
  },
};
Postfix : Expr = {
  <PostfixBase> => <>,
  <Primary> => <>,
};
PostfixNoIdent : Expr = {
  <PostfixBase> => <>,
  <PrimaryNoIdent> => <>,
};
PostfixBase : Expr = {
  <b : Postfix> "[" <e : Expr> "]" => Expr::ArrayIndex(Box::new(b), Box::new(e), None),
  <b : Postfix> "->" <i : Ident> => Expr::StructDeref(Box::new(Expr::Deref(Box::new(b), 1, None)), i, None),
  <b : Postfix> "." <i : Ident> => Expr::StructDeref(Box::new(b), i, None),
};

/// Leaves in an expression
Primary : Expr = {
  <PrimaryNoIdent> => <>,
  <i : Ident> => Expr::Variable(i, None),
};
PrimaryNoIdent : Expr = {
  "(" <Expr> ")" => <>,
  <n : Number> => Expr::Number(n),
  <b : Boolean> => Expr::Bool(b),
  "null" => Expr::Null,
  "alloc" "(" <t : Type> ")" => Expr::Alloc(t, None),
  "alloc_array" "(" <t : Type> "," <e : Expr> ")" => Expr::AllocArray(t, Box::new(e), None),
  <Call> => <>,
};

/// Expression for a function call
Call : Expr = {
  <i : Ident> "(" ")"=> Expr::Call(i, vec![], None),
  <i : Ident> "(" <e : Expr> <a : ArgFollow*> ")" => Expr::Call(
    i,
    std::iter::once(e).chain(a.into_iter()).collect::<Vec<Expr>>(),
    None
  ),
};

/// Arguments following the first one in an function call
ArgFollow : Expr = {
  "," <Expr> => <>,
};

/// Operation declarations
LOrOp: BinOp = {
  "||" => BinOp::LOr,
};
LAndOp: BinOp = {
  "&&" => BinOp::LAnd,
};
BOrOp: BinOp = {
  "|" => BinOp::Or,
};
BXorOp: BinOp = {
  "^" => BinOp::Xor,
};
BAndOp: BinOp = {
  "&" => BinOp::And,
};
EqOp: BinOp = {
  "==" => BinOp::CmpEq,
  "!=" => BinOp::CmpNeq,
};
RelOp: BinOp = {
  "<" => BinOp::Lt,
  ">" => BinOp::Gt,
  "<=" => BinOp::Lte,
  ">=" => BinOp::Gte,
};
ShiftOp: BinOp = {
  "<<" => BinOp::Sal,
  ">>" => BinOp::Sar,
};
AddOp: BinOp = {
  "+" => BinOp::Add,
  "-" => BinOp::Sub,
};
MulOp: BinOp = {
  "*" => BinOp::Mul,
  "/" => BinOp::Div,
  "%" => BinOp::Mod,
};
UnOp: UnOp = {
  "-" => UnOp::Neg,
  "~" => UnOp::Not,
  "!" => UnOp::LNot,
};
PostOp: PostOp = {
  "++" => PostOp::Inc,
  "--" => PostOp::Dec,
};
AsnOp: AsnOp = {
  "=" => AsnOp::Equal,
  "+=" => AsnOp::Plus,
  "-=" => AsnOp::Minus,
  "*=" => AsnOp::Times,
  "/=" => AsnOp::Div,
  "%=" => AsnOp::Mod,
  "&=" => AsnOp::And,
  "^=" => AsnOp::Xor,
  "|=" => AsnOp::Or,
  "<<=" => AsnOp::Sal,
  ">>=" => AsnOp::Sar,
};
